### ISSUE TITLE
XClim-related objects missing `_bc_method`

### ISSUE THREAD

**Issue by Zeitsperre** [yrobink/SBCK-python#1]
ATTN @aulemahal 

I recently switched the branch that our Xclim tests run off of from a commit made in Summer 2022 to the current development branch, and it appears we are having issues with the following tests:
```
FAILED xclim/testing/tests/test_sdba/test_adjustment.py::TestSBCKutils::test_sbck[True-SBCK_XClimNPPP] - AttributeError: 'XClimNPPP' object has no attribute '_bc_method'
FAILED xclim/testing/tests/test_sdba/test_adjustment.py::TestSBCKutils::test_sbck[True-SBCK_XClimSPPP] - AttributeError: 'XClimSPPP' object has no attribute '_bc_method'
```

For more information: https://github.com/Ouranosinc/xclim/actions/runs/4058246577/jobs/6984965020#step:6:2987

Is this something that can be easily addressed?

**Comment by yrobink** [comment]
Dear @Zeitsperre ,

I set as default value `SBCK.IdBC` for `SBCK.ppp.PrePostProcessing._bc_method`, this should solve the problem.

**Comment by Zeitsperre** [comment]
Problem is solved. Thank you!
