### ISSUE TITLE
ModuleNotFoundError: No module named 'SBCK.tools.__tools_cpp'

### ISSUE THREAD

**Issue by fangwangwf** [yrobink/SBCK-python#3]
I have above issue after successfully installed SBCK-python when import the module. More details about the error as follows. Please let me how to solve it. I had used dOTC within SBCK after successfully installed into another HPC center, but I do not have access to it. I tried to install it into another HPC center, but it comes this issue. Please help me how to solve it and thank you very much!

(SBCK_env) bash-4.2$ python3 setup.py install
running install
/glade/work/fangwang/conda-envs/SBCK_env/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/glade/work/fangwang/conda-envs/SBCK_env/lib/python3.11/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating SBCK.egg-info
writing SBCK.egg-info/PKG-INFO
writing dependency_links to SBCK.egg-info/dependency_links.txt
writing requirements to SBCK.egg-info/requires.txt
writing top-level names to SBCK.egg-info/top_level.txt
writing manifest file 'SBCK.egg-info/SOURCES.txt'
reading manifest file 'SBCK.egg-info/SOURCES.txt'
adding license file 'COPYING'
writing manifest file 'SBCK.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-311
creating build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__QMrs.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__AR2D2.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__ECBC.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__QM.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__OTC.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__init__.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__release.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__MRec.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__CDFt.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__dOTC.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__QDM.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__XClimPPP.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__R2D2.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__dTSMBC.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__IdBC.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__MBCn.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__RBC.py -> build/lib.linux-x86_64-cpython-311/SBCK
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__TSMBC.py -> build/lib.linux-x86_64-cpython-311/SBCK
creating build/lib.linux-x86_64-cpython-311/SBCK/ppp
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/ppp/__checkf.py -> build/lib.linux-x86_64-cpython-311/SBCK/ppp
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/ppp/__init__.py -> build/lib.linux-x86_64-cpython-311/SBCK/ppp
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/ppp/__PPPLinkFunction.py -> build/lib.linux-x86_64-cpython-311/SBCK/ppp
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/ppp/__PPPSSR.py -> build/lib.linux-x86_64-cpython-311/SBCK/ppp
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/ppp/__PPPNanValues.py -> build/lib.linux-x86_64-cpython-311/SBCK/ppp
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/ppp/__PrePostProcessing.py -> build/lib.linux-x86_64-cpython-311/SBCK/ppp
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/ppp/__PPPDiffRef.py -> build/lib.linux-x86_64-cpython-311/SBCK/ppp
creating build/lib.linux-x86_64-cpython-311/SBCK/tools
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/__Shift.py -> build/lib.linux-x86_64-cpython-311/SBCK/tools
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/__Dist.py -> build/lib.linux-x86_64-cpython-311/SBCK/tools
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/__SlopeStoppingCriteria.py -> build/lib.linux-x86_64-cpython-311/SBCK/tools
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/__init__.py -> build/lib.linux-x86_64-cpython-311/SBCK/tools
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/__bin_width_estimator.py -> build/lib.linux-x86_64-cpython-311/SBCK/tools
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/__shuffle.py -> build/lib.linux-x86_64-cpython-311/SBCK/tools
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/__rv_extend.py -> build/lib.linux-x86_64-cpython-311/SBCK/tools
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/__OT.py -> build/lib.linux-x86_64-cpython-311/SBCK/tools
creating build/lib.linux-x86_64-cpython-311/SBCK/metrics
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/metrics/__minkowski.py -> build/lib.linux-x86_64-cpython-311/SBCK/metrics
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/metrics/__energy.py -> build/lib.linux-x86_64-cpython-311/SBCK/metrics
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/metrics/__decorators.py -> build/lib.linux-x86_64-cpython-311/SBCK/metrics
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/metrics/__chebyshev.py -> build/lib.linux-x86_64-cpython-311/SBCK/metrics
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/metrics/__init__.py -> build/lib.linux-x86_64-cpython-311/SBCK/metrics
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/metrics/__entropy.py -> build/lib.linux-x86_64-cpython-311/SBCK/metrics
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/metrics/__euclidean.py -> build/lib.linux-x86_64-cpython-311/SBCK/metrics
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/metrics/__wasserstein.py -> build/lib.linux-x86_64-cpython-311/SBCK/metrics
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/metrics/__manhattan.py -> build/lib.linux-x86_64-cpython-311/SBCK/metrics
creating build/lib.linux-x86_64-cpython-311/SBCK/datasets
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/datasets/__init__.py -> build/lib.linux-x86_64-cpython-311/SBCK/datasets
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/datasets/__multivariates.py -> build/lib.linux-x86_64-cpython-311/SBCK/datasets
copying /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/datasets/__univariates.py -> build/lib.linux-x86_64-cpython-311/SBCK/datasets
running build_ext
creating glade
creating glade/scratch
creating glade/scratch/fangwang
icc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /glade/work/fangwang/conda-envs/SBCK_env/include -fPIC -O2 -isystem /glade/work/fangwang/conda-envs/SBCK_env/include -fPIC -I/glade/work/fangwang/conda-envs/SBCK_env/include/python3.11 -c /glade/scratch/fangwang/tmpjgginzej.cpp -o glade/scratch/fangwang/tmpjgginzej.o -std=c++14
icc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /glade/work/fangwang/conda-envs/SBCK_env/include -fPIC -O2 -isystem /glade/work/fangwang/conda-envs/SBCK_env/include -fPIC -I/glade/work/fangwang/conda-envs/SBCK_env/include/python3.11 -c /glade/scratch/fangwang/tmpor76lr_8.cpp -o glade/scratch/fangwang/tmpor76lr_8.o -fvisibility=hidden
building 'SBCK.tools.__tools_cpp' extension
creating build/temp.linux-x86_64-cpython-311
creating build/temp.linux-x86_64-cpython-311/glade
creating build/temp.linux-x86_64-cpython-311/glade/work
creating build/temp.linux-x86_64-cpython-311/glade/work/fangwang
creating build/temp.linux-x86_64-cpython-311/glade/work/fangwang/MBCn
creating build/temp.linux-x86_64-cpython-311/glade/work/fangwang/MBCn/SBCK-python-master
creating build/temp.linux-x86_64-cpython-311/glade/work/fangwang/MBCn/SBCK-python-master/SBCK
creating build/temp.linux-x86_64-cpython-311/glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools
creating build/temp.linux-x86_64-cpython-311/glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/src
icc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /glade/work/fangwang/conda-envs/SBCK_env/include -fPIC -O2 -isystem /glade/work/fangwang/conda-envs/SBCK_env/include -fPIC -I/glade/work/fangwang/conda-envs/SBCK_env/include/eigen3 -I/glade/work/fangwang/conda-envs/SBCK_env/lib/python3.11/site-packages/pybind11/include -I/glade/work/fangwang/conda-envs/SBCK_env/lib/python3.11/site-packages/pybind11/include -I/glade/work/fangwang/conda-envs/SBCK_env/include/python3.11 -c /glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/src/tools.cpp -o build/temp.linux-x86_64-cpython-311/glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/src/tools.o -O3 -DVERSION_INFO=\"0.5.0a27\" -std=c++14 -fvisibility=hidden
icpc -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/glade/work/fangwang/conda-envs/SBCK_env/lib -Wl,-rpath-link,/glade/work/fangwang/conda-envs/SBCK_env/lib -L/glade/work/fangwang/conda-envs/SBCK_env/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/glade/work/fangwang/conda-envs/SBCK_env/lib -Wl,-rpath-link,/glade/work/fangwang/conda-envs/SBCK_env/lib -L/glade/work/fangwang/conda-envs/SBCK_env/lib build/temp.linux-x86_64-cpython-311/glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/src/tools.o -o build/lib.linux-x86_64-cpython-311/SBCK/tools/__tools_cpp.cpython-311-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__QMrs.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__AR2D2.py -> build/bdist.linux-x86_64/egg/SBCK
creating build/bdist.linux-x86_64/egg/SBCK/datasets
copying build/lib.linux-x86_64-cpython-311/SBCK/datasets/__init__.py -> build/bdist.linux-x86_64/egg/SBCK/datasets
copying build/lib.linux-x86_64-cpython-311/SBCK/datasets/__multivariates.py -> build/bdist.linux-x86_64/egg/SBCK/datasets
copying build/lib.linux-x86_64-cpython-311/SBCK/datasets/__univariates.py -> build/bdist.linux-x86_64/egg/SBCK/datasets
copying build/lib.linux-x86_64-cpython-311/SBCK/__ECBC.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__QM.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__OTC.py -> build/bdist.linux-x86_64/egg/SBCK
creating build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-cpython-311/SBCK/tools/__Shift.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-cpython-311/SBCK/tools/__Dist.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-cpython-311/SBCK/tools/__SlopeStoppingCriteria.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-cpython-311/SBCK/tools/__init__.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-cpython-311/SBCK/tools/__bin_width_estimator.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-cpython-311/SBCK/tools/__shuffle.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-cpython-311/SBCK/tools/__rv_extend.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-cpython-311/SBCK/tools/__OT.py -> build/bdist.linux-x86_64/egg/SBCK/tools
copying build/lib.linux-x86_64-cpython-311/SBCK/tools/__tools_cpp.cpython-311-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/SBCK/tools
creating build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-cpython-311/SBCK/metrics/__minkowski.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-cpython-311/SBCK/metrics/__energy.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-cpython-311/SBCK/metrics/__decorators.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-cpython-311/SBCK/metrics/__chebyshev.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-cpython-311/SBCK/metrics/__init__.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-cpython-311/SBCK/metrics/__entropy.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-cpython-311/SBCK/metrics/__euclidean.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-cpython-311/SBCK/metrics/__wasserstein.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
copying build/lib.linux-x86_64-cpython-311/SBCK/metrics/__manhattan.py -> build/bdist.linux-x86_64/egg/SBCK/metrics
creating build/bdist.linux-x86_64/egg/SBCK/ppp
copying build/lib.linux-x86_64-cpython-311/SBCK/ppp/__checkf.py -> build/bdist.linux-x86_64/egg/SBCK/ppp
copying build/lib.linux-x86_64-cpython-311/SBCK/ppp/__init__.py -> build/bdist.linux-x86_64/egg/SBCK/ppp
copying build/lib.linux-x86_64-cpython-311/SBCK/ppp/__PPPLinkFunction.py -> build/bdist.linux-x86_64/egg/SBCK/ppp
copying build/lib.linux-x86_64-cpython-311/SBCK/ppp/__PPPSSR.py -> build/bdist.linux-x86_64/egg/SBCK/ppp
copying build/lib.linux-x86_64-cpython-311/SBCK/ppp/__PPPNanValues.py -> build/bdist.linux-x86_64/egg/SBCK/ppp
copying build/lib.linux-x86_64-cpython-311/SBCK/ppp/__PrePostProcessing.py -> build/bdist.linux-x86_64/egg/SBCK/ppp
copying build/lib.linux-x86_64-cpython-311/SBCK/ppp/__PPPDiffRef.py -> build/bdist.linux-x86_64/egg/SBCK/ppp
copying build/lib.linux-x86_64-cpython-311/SBCK/__init__.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__release.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__MRec.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__CDFt.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__dOTC.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__QDM.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__XClimPPP.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__R2D2.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__dTSMBC.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__IdBC.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__MBCn.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__RBC.py -> build/bdist.linux-x86_64/egg/SBCK
copying build/lib.linux-x86_64-cpython-311/SBCK/__TSMBC.py -> build/bdist.linux-x86_64/egg/SBCK
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__QMrs.py to __QMrs.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__AR2D2.py to __AR2D2.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/datasets/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/datasets/__multivariates.py to __multivariates.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/datasets/__univariates.py to __univariates.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__ECBC.py to __ECBC.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__QM.py to __QM.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__OTC.py to __OTC.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__Shift.py to __Shift.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__Dist.py to __Dist.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__SlopeStoppingCriteria.py to __SlopeStoppingCriteria.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__bin_width_estimator.py to __bin_width_estimator.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__shuffle.py to __shuffle.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__rv_extend.py to __rv_extend.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__OT.py to __OT.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__minkowski.py to __minkowski.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__energy.py to __energy.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__decorators.py to __decorators.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__chebyshev.py to __chebyshev.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__entropy.py to __entropy.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__euclidean.py to __euclidean.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__wasserstein.py to __wasserstein.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/metrics/__manhattan.py to __manhattan.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/ppp/__checkf.py to __checkf.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/ppp/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/ppp/__PPPLinkFunction.py to __PPPLinkFunction.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/ppp/__PPPSSR.py to __PPPSSR.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/ppp/__PPPNanValues.py to __PPPNanValues.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/ppp/__PrePostProcessing.py to __PrePostProcessing.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/ppp/__PPPDiffRef.py to __PPPDiffRef.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__release.py to __release.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__MRec.py to __MRec.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__CDFt.py to __CDFt.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__dOTC.py to __dOTC.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__QDM.py to __QDM.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__XClimPPP.py to __XClimPPP.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__R2D2.py to __R2D2.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__dTSMBC.py to __dTSMBC.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__IdBC.py to __IdBC.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__MBCn.py to __MBCn.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__RBC.py to __RBC.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/SBCK/__TSMBC.py to __TSMBC.cpython-311.pyc
creating stub loader for SBCK/tools/__tools_cpp.cpython-311-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/SBCK/tools/__tools_cpp.py to __tools_cpp.cpython-311.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SBCK.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/SBCK-0.5.0a27-py3.11-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing SBCK-0.5.0a27-py3.11-linux-x86_64.egg
creating /glade/work/fangwang/conda-envs/SBCK_env/lib/python3.11/site-packages/SBCK-0.5.0a27-py3.11-linux-x86_64.egg
Extracting SBCK-0.5.0a27-py3.11-linux-x86_64.egg to /glade/work/fangwang/conda-envs/SBCK_env/lib/python3.11/site-packages
Adding SBCK 0.5.0a27 to easy-install.pth file

Installed /glade/work/fangwang/conda-envs/SBCK_env/lib/python3.11/site-packages/SBCK-0.5.0a27-py3.11-linux-x86_64.egg
Processing dependencies for SBCK==0.5.0a27
Searching for pybind11==2.10.4
Best match: pybind11 2.10.4
Adding pybind11 2.10.4 to easy-install.pth file
Installing pybind11-config script to /glade/work/fangwang/conda-envs/SBCK_env/bin

Using /glade/work/fangwang/conda-envs/SBCK_env/lib/python3.11/site-packages
Finished processing dependencies for SBCK==0.5.0a27
(SBCK_env) bash-4.2$ python
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import SBCK as bc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__init__.py", line 25, in <module>
    from .__QM     import QM
  File "/glade/work/fangwang/MBCn/SBCK-python-master/SBCK/__QM.py", line 27, in <module>
    from .tools.__Dist import _Dist
  File "/glade/work/fangwang/MBCn/SBCK-python-master/SBCK/tools/__init__.py", line 21, in <module>
    from .__tools_cpp             import SparseHist
ModuleNotFoundError: No module named 'SBCK.tools.__tools_cpp'

**Comment by yrobink** [comment]
Thanks to @aulemahal for its answer `https://github.com/yrobink/SBCK/pull/5`
