### ISSUE TITLE
PyPI Package?

### ISSUE THREAD

**Issue by Zeitsperre** [yrobink/SBCK-python#5]
Hi @yrobink,

I'm wondering if you would be interested in having SBCK-python as a `pip`-installable Python package on [PyPI](https://pypi.org/). My PR (#4) fixes most of the issues that would block this package from being contributed, and the remaining work involved is miniscule (creating a user, generating a source package, uploading to PyPI with `twine`).

If this is of interest to you, I don't mind contributing some time towards this. This would be a welcome addition for `xclim`.

**Comment by yrobink** [comment]
Dear @Zeitsperre,

Thanks for your contribution, your PR is now merged. 

I had planned to make SBCK installable by pip and conda once the XSBCK (`https://github.com/yrobink/XSBCK`) development was advanced enough. I'll try to take care of it earlier.

**Comment by yrobink** [comment]
Dear @Zeitsperre ,

SBCK is now available in pypi:

https://pypi.org/project/SBCK/
